name: hypers_ui
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.hypers-ui.io/

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
